// GENERATED by scripts/update-cert-assets.mjs — do not hand-edit; re-run the script instead.
// Official badge art (self-hosted under static/certifications/), verification links, and exact
// dates from Credly (mario-belmonte.bf3fe15f) and Microsoft Learn (MarioBelmonte-3208).
import type { Certification } from './certifications';

export const certificationAssets: Record<string, Pick<Certification, 'image' | 'verifyUrl' | 'issued' | 'expires'>> = {
	"ibm-general-formulation-quantum-info": {
		"image": "/certifications/ibm-general-formulation-quantum-info.png",
		"verifyUrl": "https://www.credly.com/badges/d3c3e05e-702b-4572-9162-563cad5e5fa6",
		"issued": "2026-08-24"
	},
	"ibm-deep-learning-tensorflow": {
		"image": "/certifications/ibm-deep-learning-tensorflow.png",
		"verifyUrl": "https://www.credly.com/badges/09cf42cc-7396-4919-a5b9-22816025dd52",
		"issued": "2026-09-04"
	},
	"ibm-healthcare-jumpstart": {
		"image": "/certifications/ibm-healthcare-jumpstart.png",
		"verifyUrl": "https://www.credly.com/badges/53f4569c-8200-414f-bb60-66713f1574e5",
		"issued": "2026-09-18"
	},
	"ibm-data-viz-python": {
		"image": "/certifications/ibm-data-viz-python.png",
		"verifyUrl": "https://www.credly.com/badges/c22c58e5-c71c-494a-a254-093410e65314",
		"issued": "2026-09-04"
	},
	"ibm-quantum-safe-encryption": {
		"image": "/certifications/ibm-quantum-safe-encryption.png",
		"verifyUrl": "https://www.credly.com/badges/487203a6-9dbb-4ddf-b0fc-242c64cf20d9",
		"issued": "2026-08-25"
	},
	"ibm-basics-quantum-info": {
		"image": "/certifications/ibm-basics-quantum-info.png",
		"verifyUrl": "https://www.credly.com/badges/9359e20d-fd60-4936-a9aa-2e38e58bea3d",
		"issued": "2026-08-20"
	},
	"ibm-fundamentals-quantum-algorithms": {
		"image": "/certifications/ibm-fundamentals-quantum-algorithms.png",
		"verifyUrl": "https://www.credly.com/badges/62e61491-84a3-4f54-887b-89d749b644fd",
		"issued": "2026-08-14"
	},
	"ibm-kafka-pipelines": {
		"image": "/certifications/ibm-kafka-pipelines.png",
		"verifyUrl": "https://www.credly.com/badges/d19f1354-b19f-4a69-9f97-795900738a60",
		"issued": "2026-08-12"
	},
	"ibm-edt-practitioner": {
		"image": "/certifications/ibm-edt-practitioner.png",
		"verifyUrl": "https://www.credly.com/badges/a1a776be-a521-46fa-b823-b8103f0a13cb",
		"issued": "2026-08-11"
	},
	"ibm-garage-essentials": {
		"image": "/certifications/ibm-garage-essentials.png",
		"verifyUrl": "https://www.credly.com/badges/e6c6affa-f2fd-4a4e-975f-ac7abc6991c1",
		"issued": "2026-08-11"
	},
	"ibm-garage-foundation": {
		"image": "/certifications/ibm-garage-foundation.png",
		"verifyUrl": "https://www.credly.com/badges/ba6cc1fb-3864-4fdc-a4dd-2fc675438166",
		"issued": "2026-08-11"
	},
	"ibm-containers-kubernetes": {
		"image": "/certifications/ibm-containers-kubernetes.png",
		"verifyUrl": "https://www.credly.com/badges/d3425dfa-a47b-43fb-879f-aec26583af7d",
		"issued": "2026-07-31"
	},
	"ibm-trustworthy-ai": {
		"image": "/certifications/ibm-trustworthy-ai.png",
		"verifyUrl": "https://www.credly.com/badges/22f05a4f-8840-4eb1-bd88-664800d6db15",
		"issued": "2026-07-31"
	},
	"ibm-method-essential": {
		"image": "/certifications/ibm-method-essential.png",
		"verifyUrl": "https://www.credly.com/badges/0e788a39-6ec9-4db3-8db2-79615cf8367b",
		"issued": "2026-07-30"
	},
	"ibm-python-data-science": {
		"image": "/certifications/ibm-python-data-science.png",
		"verifyUrl": "https://www.credly.com/badges/0702aa05-1975-468d-987d-07d04bca155e",
		"issued": "2026-07-27"
	},
	"ibm-deep-learning-essentials": {
		"image": "/certifications/ibm-deep-learning-essentials.png",
		"verifyUrl": "https://www.credly.com/badges/8531aed7-b808-4dfa-b5ef-b5279eaf13d2",
		"issued": "2026-07-25"
	},
	"ibm-statistics-101": {
		"image": "/certifications/ibm-statistics-101.png",
		"verifyUrl": "https://www.credly.com/badges/06bc99d5-e0e0-49b7-9981-8b396894ff69",
		"issued": "2026-07-25"
	},
	"ibm-think-like-a-hacker": {
		"image": "/certifications/ibm-think-like-a-hacker.png",
		"verifyUrl": "https://www.credly.com/badges/4be5b21a-7328-45f3-9e05-82a5c3b13a15",
		"issued": "2026-07-25"
	},
	"ibm-docker-essentials": {
		"image": "/certifications/ibm-docker-essentials.png",
		"verifyUrl": "https://www.credly.com/badges/cdb7117f-8542-477f-87f7-888b31907b47",
		"issued": "2026-07-25"
	},
	"ibm-data-analysis-python": {
		"image": "/certifications/ibm-data-analysis-python.png",
		"verifyUrl": "https://www.credly.com/badges/93885fd4-7d2b-4d52-b825-234a63dd7c82",
		"issued": "2026-07-24"
	},
	"ibm-data-viz-r": {
		"image": "/certifications/ibm-data-viz-r.png",
		"verifyUrl": "https://www.credly.com/badges/3bbc5b7f-63d2-456a-b2cb-ee37919fdbaa",
		"issued": "2026-07-24"
	},
	"ibm-cloud-native-multicloud": {
		"image": "/certifications/ibm-cloud-native-multicloud.png",
		"verifyUrl": "https://www.credly.com/badges/83dc62c3-61f9-4516-b7f9-bd333c93b772",
		"issued": "2026-07-24"
	},
	"ibm-cloud-essentials": {
		"image": "/certifications/ibm-cloud-essentials.png",
		"verifyUrl": "https://www.credly.com/badges/c12f10d1-4f12-4fd3-8aee-3ea2234e781b",
		"issued": "2026-07-24"
	},
	"ibm-quantum-business-foundations": {
		"image": "/certifications/ibm-quantum-business-foundations.png",
		"verifyUrl": "https://www.credly.com/badges/74088cbc-b102-40b6-939d-7f78e6c7d46e",
		"issued": "2026-07-22"
	},
	"ibm-generative-agentic-ai": {
		"image": "/certifications/ibm-generative-agentic-ai.png",
		"verifyUrl": "https://www.credly.com/badges/73d09efb-7aa5-469b-8915-343ac8deaa28",
		"issued": "2026-07-23",
		"expires": "2027-07-23"
	},
	"ibm-bob-intermediate": {
		"image": "/certifications/ibm-bob-intermediate.png",
		"verifyUrl": "https://www.credly.com/badges/a17fc11b-b1e4-41ed-839c-1d90ceb19d30",
		"issued": "2026-08-25",
		"expires": "2027-08-25"
	},
	"ibm-growth-behaviors": {
		"image": "/certifications/ibm-growth-behaviors.png",
		"verifyUrl": "https://www.credly.com/badges/2652634a-fdd1-4ba4-9447-7941279670c3",
		"issued": "2026-09-22",
		"expires": "2036-09-22"
	},
	"gcp-gemini-enterprise-agent-dev": {
		"image": "/certifications/gcp-gemini-enterprise-agent-dev.png",
		"verifyUrl": "https://www.credly.com/badges/138fc26b-516f-4c64-8176-f3bd5682275a",
		"issued": "2026-09-21",
		"expires": "2027-03-21"
	},
	"anthropic-claude-certified-architect-pro": {
		"image": "/certifications/anthropic-claude-certified-architect-pro.png",
		"verifyUrl": "https://www.credly.com/badges/c350d3de-531c-4bb8-b27e-6592c9ec31af",
		"issued": "2026-09-18",
		"expires": "2027-09-18"
	},
	"ms-dp-900": {
		"image": "/certifications/ms-dp-900.svg",
		"verifyUrl": "https://learn.microsoft.com/api/credentials/share/en-us/MarioBelmonte-3208/4D3C439254C7EA10?sharingId=8AECAE02766AB685",
		"issued": "2026-09-15"
	},
	"ms-ai-901": {
		"image": "/certifications/ms-ai-901.svg",
		"verifyUrl": "https://learn.microsoft.com/api/credentials/share/en-us/MarioBelmonte-3208/BC3090331776AE47?sharingId=8AECAE02766AB685",
		"issued": "2026-09-08"
	},
	"ms-gh-300": {
		"image": "/certifications/ms-gh-300.svg",
		"verifyUrl": "https://learn.microsoft.com/api/credentials/share/en-us/MarioBelmonte-3208/91F59D11910C3DFC?sharingId=8AECAE02766AB685",
		"issued": "2026-10-05",
		"expires": "2028-10-05"
	},
	"anthropic-claude-certified-dev-foundations": {
		"image": "/certifications/anthropic-claude-certified-dev-foundations.png",
		"verifyUrl": "https://www.credly.com/badges/afcb5081-1dcc-454e-a06a-a0c00f7980e6",
		"issued": "2026-08-28",
		"expires": "2027-08-28"
	},
	"anthropic-claude-partner-claude-code": {
		"image": "/certifications/anthropic-claude-partner-claude-code.png",
		"verifyUrl": "https://www.credly.com/badges/b79213ea-b0a3-49a7-9788-e0001208743c",
		"issued": "2026-09-08",
		"expires": "2027-03-08"
	},
	"gcp-build-with-gemini": {
		"image": "/certifications/gcp-build-with-gemini.png",
		"verifyUrl": "https://www.credly.com/badges/d68427d0-3d93-4015-8a64-2b3925a1e5d3",
		"issued": "2026-09-28"
	},
	"gcp-antigravity": {
		"image": "/certifications/gcp-antigravity.png",
		"verifyUrl": "https://www.credly.com/badges/3981c564-d59b-4a28-aafd-5da64132e4a7",
		"issued": "2026-09-21"
	},
	"gcp-adk-evaluate": {
		"image": "/certifications/gcp-adk-evaluate.png",
		"verifyUrl": "https://www.credly.com/badges/bfdc37f3-e5b8-479a-9702-84b920baf0c3",
		"issued": "2026-09-21"
	},
	"gcp-adk-deploy": {
		"image": "/certifications/gcp-adk-deploy.png",
		"verifyUrl": "https://www.credly.com/badges/a365f695-7093-4c36-bb0a-f0fbbb35214d",
		"issued": "2026-09-21"
	},
	"redhat-ai-platform-tdp-seller": {
		"image": "/certifications/redhat-ai-platform-tdp-seller.png",
		"verifyUrl": "https://www.credly.com/badges/8c5b5760-2c1c-4d29-bf1e-ea224b6f0e26",
		"issued": "2026-09-18",
		"expires": "2027-09-19"
	},
	"redhat-2026-portfolio-seller-foundational": {
		"image": "/certifications/redhat-2026-portfolio-seller-foundational.png",
		"verifyUrl": "https://www.credly.com/badges/3ca5d176-c757-4d0c-9a00-e0b39a0af688",
		"issued": "2026-09-18",
		"expires": "2027-09-19"
	},
	"servicenow-delivery-ai-agents": {
		"image": "/certifications/servicenow-delivery-ai-agents.png",
		"verifyUrl": "https://www.credly.com/badges/2f8f6d47-9778-465d-999d-65ba5ef2bbd1",
		"issued": "2026-09-17"
	}
};
