// Generated by scripts/update-project-language-bytes.mjs
// Last updated: 2026-04-08T18:32:51.262Z

export const projectLanguageBytes: Record<string, number> = {
	'auto-docker': 26506,
	'clear-cites': 60669,
	'cmu-march-madness-ml': 190512,
	'discord-music-bot': 17906,
	'file-port': 133025,
	'idea-db': 45421,
	'job-apply': 72719,
	'little-guy': 121218,
	'min-gpt-copy': 69958,
	'mini-gamba': 870275,
	'mono-pix-scout': 19162,
	'phone-ctrl': 85784,
	'repo-nav-touch': 91918,
	'rune-lo-ldb': 75816,
	'sheet-music-gen': 27800,
	'shorts-blocker': 18048,
	'smart-desktop': 73715,
	'smart-home-iot-dashboard': 403984,
	'song-recs': 61832,
	'streamer-stalker': 152818,
	'tech-stack-analyzer': 80341,
	'to-do-or-destroy': 163860,
	'visual-budget-planner': 653498,
	'wifi-scan': 50078,
	'yt-to-mp3': 8895
};
